### ISSUE TITLE
When installing into an app that uses services or concerns, app fails to start

### ISSUE THREAD

**Issue by mikel** [wallaby-rails/wallaby-rails#1]
When trying to boot with classes within `app/controllers/concerns` or `app/models/concerns` or `app/services` Wallaby fails to start with:

```
/Users/mikel/.rvm/gems/ruby-2.1.6@enlight/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:495:in `load_missing_constant': Unable to autoload constant GenerateEnrollmentsCsvService, expected /Users/mikel/Code/enlight/app/services/generate_enrollments_csv_service.rb to define it (LoadError)
    from /Users/mikel/.rvm/gems/ruby-2.1.6@enlight/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:184:in `const_missing'
    from /Users/mikel/.rvm/gems/ruby-2.1.6@enlight/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:261:in `const_get'
    from /Users/mikel/.rvm/gems/ruby-2.1.6@enlight/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:261:in `block in constantize'
    from /Users/mikel/.rvm/gems/ruby-2.1.6@enlight/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `each'
    from /Users/mikel/.rvm/gems/ruby-2.1.6@enlight/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `inject'
    from /Users/mikel/.rvm/gems/ruby-2.1.6@enlight/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `constantize'
    from /Users/mikel/.rvm/gems/ruby-2.1.6@enlight/gems/activesupport-4.2.6/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
    from /Users/mikel/.rvm/gems/ruby-2.1.6@enlight/gems/wallaby-4.0.1/app/routes/wallaby/resources_router.rb:13:in `block in <top (required)>'
    from /Users/mikel/.rvm/gems/ruby-2.1.6@enlight/gems/wallaby-4.0.1/app/routes/wallaby/resources_router.rb:11:in `each'
    from /Users/mikel/.rvm/gems/ruby-2.1.6@enlight/gems/wallaby-4.0.1/app/routes/wallaby/resources_router.rb:11:in `<top (required)>'
```

Changing the service from:

```
class GenerateEnrollmentsCSVService
end
```

to

```
module Service
  class GenerateEnrollmentsCSVService
  end
end
```

Does fix it, but you have to set this everywhere in the app. Wallaby should be able to handle these classes on usual Rails paths without further modification like the rest of Rails can.

**Comment by tian-im** [comment]
Upgrade to 4.0.1 should fix it.

What it does in resources_router is that it tries to preload all the constants in `app` folder, this is because in dev environment, all classes are lazy loaded, and wallaby is relying on subclasses to make the magics.

I will yank 4.0.0 for now.

**Comment by tian-im** [comment]
And BTW the class name for generate_enrollments_csv_service.rb should be `GenerateEnrollmentsCsvService` instead of `GenerateEnrollmentsCSVService` (`Csv` instead of `CSV`), I guess Rails won't load it correctly according to its naming convention.

**Comment by tian-im** [comment]
Please let me know if 4.0.1 resolves your problem.

**Comment by mikel** [comment]
Getting a similar issue @tian-im 

```
/Users/mikel/.rvm/gems/ruby-2.1.6@enlight/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:495:in `load_missing_constant':
Unable to autoload constant Concerns::Localeable,
expected /Users/mikel/Code/enlight/app/models/concerns/localeable.rb to define it (LoadError)
```

The file in question is:

``` ruby
# /app/models/concerns/localeable.rb
module Localeable
  extend ActiveSupport::Concern
end
```

**Comment by tian-im** [comment]
Could you try the 4.1.0? see the commit above, should solve it now.

**Comment by mikel** [comment]
Awesome @tian-im, app is starting now :)
