### ISSUE TITLE
Unable to autoload constant Concerns

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#169]
I am seeing a lot of these lines in the development log when making changes to our app and loading a page:

```
[WALLABY] Preload warning: Unable to autoload constant Concerns::Importable ...
```

Where `Importable` is the name of a concern. It does this for every concern module defined in the app.

Also changes made to any wallaby subclass does not seem to take effect. I think it may be related to this.

I haven't had time to dive into this further so perhaps this is an issue with our app config and would happen with any engine. I'll comment on this if I find out more.

Wallaby version: 6.1.0
Rails version: 5.2.4.1

**Comment by ryanb** [comment]
I was able to duplicate this problem in the [demo app](https://github.com/tian-im/wallaby_demo). I upgraded it to wallaby 6 and added a concern. When I update some code and reload the page I get:

```
  [WALLABY] Reloading...
  [WALLABY] Preload warning: uninitialized constant Ability::CanCan from /Users/rbates/code/gh/wallaby_demo/app/models/ability.rb
["/Users/rbates/code/gh/wallaby_demo/app/models/ability.rb:2:in `<class:Ability>'", "/Users/rbates/code/gh/wallaby_demo/app/models/ability.rb:1:in `<top (required)>'", "/Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'", "/Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'", "/Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:13:in `loading'"]
  [WALLABY] Preload warning: Unable to autoload constant Concerns::Foo, expected /Users/rbates/code/gh/wallaby_demo/app/models/concerns/foo.rb to define it from /Users/rbates/code/gh/wallaby_demo/app/models/concerns/foo.rb
["/Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:511:in `load_missing_constant'", "/Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:195:in `const_missing'", "/Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/inflector/methods.rb:298:in `const_get'", "/Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/inflector/methods.rb:298:in `block in constantize'", "/Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/inflector/methods.rb:281:in `each'"]
Model Application cannot be found.
Model Application cannot be found.
Model Application cannot be found.
Model Application cannot be found.
Model Application cannot be found.
```

Also changes do not take effect until I restart the server on the demo app either.

**Comment by tian-im** [comment]
I was using constantize to preload all the classes, this doesn't work really well.

There was a problem that I didn't go for `require_dependency`, but I can't remember that now.

Let me switch it back to `require_dependency` and see if it makes things differently.

**Comment by tian-im** [comment]
@ryanb could you upgrade wallaby to 6.1.2 and see if it works for you?

**Comment by ryanb** [comment]
Looks like it's working, nice!
