### ISSUE TITLE
Missing translation in 6.1.4

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#203]
I'm seeing a missing translation error since upgrading Wallaby from 6.1.3 to 6.1.4 (on Rails 6.1.4)

```
ActionView::Template::Error:
  translation missing: en-US.wallaby.map.missing_mode_for_model_class
# ./config/initializers/localeapp.rb:31:in `call'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n.rb:382:in `handle_exception'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.8.11/lib/i18n.rb:212:in `translate'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-core-0.2.3/lib/utils/wallaby/locale.rb:18:in `call'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-core-0.2.3/lib/utils/wallaby/locale.rb:18:in `t'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-core-0.2.3/lib/wallaby/map.rb:163:in `map_of'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-core-0.2.3/lib/wallaby/map.rb:106:in `authorizer_map'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-core-0.2.3/lib/concerns/wallaby/authorizable.rb:93:in `authorizer_of'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-core-0.2.3/lib/concerns/wallaby/authorizable.rb:73:in `authorized?'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-core-0.2.3/lib/concerns/wallaby/authorizable.rb:83:in `unauthorized?'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-core-0.2.3/lib/helpers/wallaby/links_helper.rb:42:in `new_link'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-6.1.4/app/views/wallaby/resources/show/_has_many.html.erb:9:in `___sers_rbates__rbenv_versions_______lib_ruby_gems_______gems_wallaby_______app_views_wallaby_resources_show__has_many_html_erb__4206216278495891214_169900'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/base.rb:247:in `public_send'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/base.rb:247:in `_run'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/template.rb:154:in `block in render'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb:205:in `instrument'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/template.rb:345:in `instrument_render_template'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/template.rb:152:in `render'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb:203:in `block in instrument'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb:203:in `instrument'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/renderer/partial_renderer.rb:271:in `render'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/renderer/renderer.rb:53:in `render_partial'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/helpers/rendering_helper.rb:45:in `render'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-core-0.2.3/lib/services/wallaby/type_renderer.rb:16:in `render'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-core-0.2.3/lib/helpers/wallaby/resources_helper.rb:23:in `type_render'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-6.1.4/app/views/wallaby/resources/show.html.erb:17:in `block in ___sers_rbates__rbenv_versions_______lib_ruby_gems_______gems_wallaby_______app_views_wallaby_resources_show_html_erb__691929870940969589_169760'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-6.1.4/app/views/wallaby/resources/show.html.erb:14:in `each'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/wallaby-6.1.4/app/views/wallaby/resources/show.html.erb:14:in `___sers_rbates__rbenv_versions_______lib_ruby_gems_______gems_wallaby_______app_views_wallaby_resources_show_html_erb__691929870940969589_169760'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/base.rb:247:in `public_send'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/base.rb:247:in `_run'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/template.rb:154:in `block in render'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb:205:in `instrument'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/template.rb:345:in `instrument_render_template'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/template.rb:152:in `render'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb:203:in `block in instrument'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb:203:in `instrument'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.4/lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb:203:in `block in instrument'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
# /Users/rbates/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb:203:in `instrument'
```

Any ideas?

**Comment by tian-im** [comment]
@ryanb `wallaby` only has translation in `en`, it looks like your current locale is `en-US`, therefore, you might want to set the locale fallbacks like this so that it can pick up the `en` translation:

```
config.i18n.fallbacks = [:en]
```

**Comment by ryanb** [comment]
It's strange that this issue didn't show up until I upgraded to wallaby-core 0.2.3. What's even stranger is upgrading to wallaby-core 0.2.4 seems to have fixed this issue. Not sure why since the changes appear unrelated to i18n. Oh well, at least it's working, closing!
